[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_first_project = "Bxt2pzDoJ5zKbbLeC1u2qDa66YrLX8zLiRdgL6iNp6R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/deepak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
